using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace OROCHI
{
    //ƒvƒŒƒCƒ„[‚ª“G‚Ì‰“‹——£UŒ‚”ÍˆÍ‚ÉN“üA’Eo‚Ìˆ—
    public class LongAttackArea : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("e‚ÌƒXƒNƒŠƒvƒg‚ğæ“¾")]
        Enemy Parent_Enemy = null;

        //“G‚ÌUŒ‚”ÍˆÍ‚Ö‚ÌN“ü”»’è
        private void OnTriggerEnter(Collider colision)
        {
            //Player‚ª‰“‹——£UŒ‚”Í“à‚ÉN“ü
            if (colision.CompareTag("Player"))
            {
                Parent_Enemy.isLongAttacks = true;
                //‰“‹——£UŒ‚ƒXƒe[ƒg‚É•ÏX
                Parent_Enemy.LongAttack(); 
            }
        }

        //“G‚Ì‰“‹——£UŒ‚”»’è‚©‚ç‚Ì’Eo‚Ì”»’è
        private void OnTriggerExit(Collider colision)
        {
            //Player‚ª‰“‹——£UŒ‚”ÍŠO‚É’Eo
            if (colision.CompareTag("Player"))
            {
                Parent_Enemy.isLongAttacks = false;
                Parent_Enemy.SetDiscoverState();
            }
        }
    }
}
